services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/people_analytics
      - REDIS_URL=redis://redis:6379
      - DEEPSEEK_ENDPOINT=http://deepseek-ollama:11434
    depends_on:
      - postgres
      - redis
      - deepseek-ollama
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=people_analytics
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  deepseek-ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./data/ollama:/root/.ollama
    command: serve

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://deepseek-ollama:11434/api
    depends_on:
      - deepseek-ollama

volumes:
  postgres_data:
  redis_data:
  ollama_data:
